default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.3.0'
    hooks:
      - id: mypy
        additional_dependencies:
          - types-setuptools
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
# NOTEBOOKS:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black-jupyter
        name: black (jupyter)
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-isort
        name: isort (jupyter)
#  - repo: https://github.com/roy-ht/pre-commit-jupyter
#    rev: v1.2.1
#    hooks:
#      - id: jupyter-notebook-cleanup
#        args:
#          - --remove-kernel-metadata
#          - --pin-patterns
#          - "[pin];[donotremove]"
