default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/ambv/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.14.1'
    hooks:
      - id: mypy
        additional_dependencies:
          - types-setuptools
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
# NOTEBOOKS:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black-jupyter
        name: black (jupyter)
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-isort
        name: isort (jupyter)
#  - repo: https://github.com/roy-ht/pre-commit-jupyter
#    rev: v1.2.1
#    hooks:
#      - id: jupyter-notebook-cleanup
#        args:
#          - --remove-kernel-metadata
#          - --pin-patterns
#          - "[pin];[donotremove]"
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
        exclude: ^(api/docs/source/includes/api/|.gitlab/issue_templates/)
        args:
          - "--disable=MD013"
          - "--disable=MD034"
          - "--disable=MD040"
          - "--fix"
