[build-system]
requires = ["setuptools>=42", "wheel", "pybind11>=2.9.0", "pyarrow>=7.0.0"]
build-backend = "setuptools.build_meta"


[tool.isort]
profile = "black"
line_length = 120

[tool.black]
line-length = 120
target-version = ['py38']

[mypy]
python_version = 3.9

